# Generated by Django 3.1.7 on 2021-04-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0002_auto_20210411_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='author',
        ),
    ]
