# Generated by Django 3.1.7 on 2021-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0003_auto_20210411_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='C/', upload_to='pics'),
            preserve_default=False,
        ),
    ]
