# Generated by Django 3.1.7 on 2021-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.CharField(max_length=10),
        ),
    ]
