# Generated by Django 3.1.7 on 2021-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0006_auto_20210411_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
